In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
data = {
    'Name': ['Arun', 'Bharat', 'Charan', 'Divya', 'Esha', 'Farhan'],
    'Age': [21, 22, np.nan, 24, 23, 25],
    'Salary': [20000, 25000, 30000, np.nan, 28000, 35000],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'HR', 'Sales']
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

     Name   Age   Salary Department
0    Arun  21.0  20000.0         IT
1  Bharat  22.0  25000.0         HR
2  Charan   NaN  30000.0         IT
3   Divya  24.0      NaN      Sales
4    Esha  23.0  28000.0         HR
5  Farhan  25.0  35000.0      Sales

In [4]:
print("First five rows:")
display(df.head())

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
display(df.describe(include='all'))

print("\nMissing values:")
print(df.isnull().sum())

First five rows:

     Name   Age   Salary Department
0    Arun  21.0  20000.0         IT
1  Bharat  22.0  25000.0         HR
2  Charan   NaN  30000.0         IT
3   Divya  24.0      NaN      Sales
4    Esha  23.0  28000.0         HR

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Salary      5 non-null      float64
 3   Department  6 non-null      object
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

Statistical summary:

        Name        Age        Salary Department
count      6   5.000000      5.000000          6
unique     6        NaN           NaN          3
top     Arun        NaN           NaN         IT
freq       1        NaN           NaN          2
mean     NaN  23.000000  27600.000000        NaN
std      NaN   1.581139   5594.640292        NaN
min      NaN  21.000000  20000.000000        NaN
25%      NaN  22.000000  25000.000000        NaN
50%      NaN  23.000000  28000.000000        NaN
75%      NaN  24.000000  30000.000000        NaN
max      NaN  25.000000  35000.000000        NaN

Missing values:
Name          0
Age           1
Salary        1
Department    0
dtype: int64

In [5]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

print("Dataset after handling missing values:")
display(df)

print("\nRemaining missing values:")
print(df.isnull().sum())

Dataset after handling missing values:

     Name   Age   Salary Department
0    Arun  21.0  20000.0         IT
1  Bharat  22.0  25000.0         HR
2  Charan  23.0  30000.0         IT
3   Divya  24.0  27600.0      Sales
4    Esha  23.0  28000.0         HR
5  Farhan  25.0  35000.0      Sales

Remaining missing values:
Name          0
Age           0
Salary        0
Department    0
dtype: int64

In [6]:
df_encoded = pd.get_dummies(
    df,
    columns=['Department'],
    dtype=int
)

print("Dataset after encoding:")
display(df_encoded)

Dataset after encoding:

     Name   Age   Salary  Department_HR  Department_IT  Department_Sales
0    Arun  21.0  20000.0              0              1                 0
1  Bharat  22.0  25000.0              1              0                 0
2  Charan  23.0  30000.0              0              1                 0
3   Divya  24.0  27600.0              0              0                 1
4    Esha  23.0  28000.0              1              0                 0
5  Farhan  25.0  35000.0              0              0                 1

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_encoded[['Age', 'Salary']] = scaler.fit_transform(
    df_encoded[['Age', 'Salary']]
)

print("Dataset after normalization:")
display(df_encoded)

Dataset after normalization:

     Name   Age    Salary  Department_HR  Department_IT  Department_Sales
0    Arun  0.00  0.000000              0              1                 0
1  Bharat  0.25  0.333333              1              0                 0
2  Charan  0.50  0.666667              0              1                 0
3   Divya  0.75  0.506667              0              0                 1
4    Esha  0.50  0.533333              1              0                 0
5  Farhan  1.00  1.000000              0              0                 1

In [8]:
df_encoded.to_csv('processed_dataset.csv', index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [9]:
from google.colab import files

files.download('processed_dataset.csv')